font:
  size: 16
  AppleFontSmoothing: true
  normal:
    family: MonoLisa
TERM: xterm-256color
shell:
  program: ubuntu
  args:
    - --login
window:
  opacity: 0.98
import:
  - ~/.config/alacritty/themes/themes/nightfox.yaml
